server:
  port: 8083

spring:
  application:
    name: cities-service
  datasource:
    url: jdbc:mysql://localhost:3306/cities_service?serverTimezone=UTC
    username: root
    password: "1234"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka